### ISSUE TITLE
git学習メモの作成

### ISSUE THREAD

**Issue by Daaaai0809** [Daaaai0809/hello-world#2]
## 概要

 - [x] readmeにgit学習メモのリンクを張る
 - [x] githubフローに関する説明を追加する
 - [ ] 全体的に見直し体制を整える

**Comment by Daaaai0809** [comment]
@warayuki 

多分なんですけど、mainブランチにそのままpushしてる気がします！
演習ではissueのbranch切って`git-tutorial.md` `README.md`の修正を行いPR(プルリクエスト)を作成するって流れだったはずだと思います 💦

**Comment by ghost** [comment]
なんも分かってなくて編集しちゃいました💦ご迷惑おかけしました。
一旦追加してしまった部分削除しましたので、ご確認お願いします。


2023/07/12 18:12、Dai Tsuruga ***@***.***>のメール:

﻿

@warayuki<https://github.com/warayuki>

多分なんですけど、mainブランチにそのままpushしてる気がします！
演習ではbranch切ってgit-tutorial.md``README.mdの修正を行いPRを作成するって流れだったはずだと思います 💦

**Comment by Daaaai0809** [comment]
削除確認できました！

ブランチ一応今回の課題の流れとしては
- CodeSpaceでbranchを切る
   - CodeSpaceのターミナルで `$ git checkout -b <ブランチ名>`を実行すると新たにブランチを作成して一緒にブランチの移動もしてくれます！
   - この画像であれば `@Daaaai0809 ➜ /workspaces/hello-world (main) $`以降に先ほどのコマンドを打てば〇です。($は付けない)
 ![スクリーンショット (3)](https://github.com/Daaaai0809/hello-world/assets/130345626/e8042184-90cf-4e08-9861-96da1a9b3e9f)

- `git-tutorial.md` `README.md`修正
- 修正が完了したら以下の順にコマンドを打つ
    - `$ git add .`
    - `$ git commit -m "<コミットメッセージ>"`
    - `$ git push -u origin <ブランチ名>`
- プルリクエストの作成(ヘッダーメニューの**Pull Request**に飛ぶと上の方に**Create PullRequest**という緑のボタンが現れるはずです！！)
- 適当にTitle, 内容を入力してPRを作成すれば終わり！！

って感じになると思います！
わからないことあったら聞いてください 👍

**Comment by Daaaai0809** [comment]
@warayuki 

> なんも分かってなくて編集しちゃいました💦ご迷惑おかけしました。

全然大丈夫です 🙆‍♂️ 

削除確認できました！

一応今回の課題の流れとしては
- CodeSpaceでbranchを切る
   - CodeSpaceのターミナルで `$ git checkout -b <ブランチ名>`を実行すると新たにブランチを作成して一緒にブランチの移動もしてくれます！
   - この画像であれば `@Daaaai0809 ➜ /workspaces/hello-world (main) $`以降に先ほどのコマンドを打てば〇です。($は付けない)
 ![スクリーンショット (3)](https://github.com/Daaaai0809/hello-world/assets/130345626/e8042184-90cf-4e08-9861-96da1a9b3e9f)

- `git-tutorial.md` `README.md`修正
- 修正が完了したら以下の順にコマンドを打つ
    - `$ git add .`
    - `$ git commit -m "<コミットメッセージ>"` (コミットメッセージは何でもいいです)
    - `$ git push -u origin <ブランチ名>`
- プルリクエストの作成(ヘッダーメニューの**Pull Request**に飛ぶと上の方に**Create PullRequest**という緑のボタンが現れるはずです！！)
- 適当にTitle, 内容を入力してPRを作成すれば終わり！！

って感じになると思います！
わからないことあったら聞いてください 👍

**Comment by ghost** [comment]
ご丁寧にありがとうございます🥺
また変なことしてしまっていたら教えていただきたいです🙇‍♀️

2023/07/13 11:23、Dai Tsuruga ***@***.***>のメール:

﻿

@warayuki<https://github.com/warayuki>

削除確認できました！

一応今回の課題の流れとしては

  *   CodeSpaceでbranchを切る

     *   CodeSpaceのターミナルで $ git checkout -b <ブランチ名>を実行すると新たにブランチを作成して一緒にブランチの移動もしてくれます！
     *   この画像であれば @Daaaai0809 ➜ /workspaces/hello-world (main) $以降に先ほどのコマンドを打てば〇です。($は付けない)
[スクリーンショット (3)]<https://user-images.githubusercontent.com/130345626/253139959-e8042184-90cf-4e08-9861-96da1a9b3e9f.png>
  *   git-tutorial.md README.md修正

  *   修正が完了したら以下の順にコマンドを打つ

     *   $ git add .
     *   $ git commit -m "<コミットメッセージ>"
     *   $ git push -u origin <ブランチ名>
  *   プルリクエストの作成(ヘッダーメニューのPull Requestに飛ぶと上の方にCreate PullRequestという緑のボタンが現れるはずです！！)

  *   適当にTitle, 内容を入力してPRを作成すれば終わり！！

って感じになると思います！
わからないことあったら聞いてください 👍
